INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('rodrigou','torrasds','30894231','calle falsa129');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('diego','torres','30894225','calle falsa123');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('marcos','torreas','30894223','calle falsa124');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');
INSERT INTO empleados (nombre, apellido, dni, direccion) VALUES ('Mariano','torrentes','30894222','calle falsa126');

INSERT INTO tipos_habitacion (id,nombre, descrip,cant_huespedes) VALUES (1,'Single','Pequeña',1);
INSERT INTO tipos_habitacion (id,nombre, descrip,cant_huespedes) VALUES (2,'Doble','Doble we',2);
INSERT INTO tipos_habitacion (id,nombre, descrip,cant_huespedes) VALUES (3,'Triple','Doble we',3);
INSERT INTO tipos_habitacion (id,nombre, descrip,cant_huespedes) VALUES (4,'Multiple','Doble we',8);

INSERT INTO tematicas (id,nombre, descrip) VALUES (1,'Amazonas','Amazonas we');
INSERT INTO tematicas (id,nombre, descrip) VALUES (2,'Montañal','ñañañewee we');
INSERT INTO tematicas (id,nombre, descrip) VALUES (3,'80','Son los 80 we');

INSERT INTO habitaciones (num_id,precio_noche,tematica_id,tipo_hab_id) VALUES('12121212',90.0,1,1);
INSERT INTO habitaciones (num_id,precio_noche,tematica_id,tipo_hab_id) VALUES('1212121',100.0,2,3);
INSERT INTO habitaciones (num_id,precio_noche,tematica_id,tipo_hab_id) VALUES('12121212',96.0,3,4);
INSERT INTO habitaciones (num_id,precio_noche,tematica_id,tipo_hab_id) VALUES('12121212',113.0,1,2);
INSERT INTO habitaciones (num_id,precio_noche,tematica_id,tipo_hab_id) VALUES('12121212',108.0,2,3);

INSERT INTO usuarios (username,password,enabled) VALUES('admin','$2a$10$uyj4LFniG/jI/WX76YHPxeRZw7gShzLKLHSj5PXQm..qyfq4i10L2',1);
INSERT INTO usuarios (username,password,enabled) VALUES('andres','$2a$10$WoZpkFi.7jeXk4PL8uGf4.T/2XdbAqcE8Fcva5HIAzaPTaeI2bcM',1);

INSERT INTO roles (nombre) VALUES('ROLE_USER');
INSERT INTO roles (nombre) VALUES('ROLE_ADMIN');

INSERT INTO usuarios_roles (usuario_id,rol_id) VALUES(1,1);
INSERT INTO usuarios_roles (usuario_id,rol_id) VALUES(2,2);
INSERT INTO usuarios_roles (usuario_id,rol_id) VALUES(2,1);
